#!/bin/bash

##$ -l magnycours
#$ -pe singlenode 1

#$ -l long

#$ -A r_ashwin
#$ -M r_ashwin@mit.edu
##$ -m ae
##$ -l h_rt=1732000
#$ -l h_rt=1008:00:00


#$ -N binaryLLE
#$ -o binaryLLE.out
#$ -e binaryLLE.err
#$ -j y

#$ -V
#$ -cwd

# export MPICH2_ROOT=/opt/mpich2-1.0.8/
export PATH=$MPICH2_ROOT/bin:$PATH
export MPD_CON_EXT="sge_$JOB_ID.$TASK_ID"

echo "Got $NSLOTS slots."
# The order of arguments is important. First global, then local options.
##cat $TMPDIR/machines

matlab13 -nodisplay -r "binaryLLE, exit"
